name: Build on Windows and Linux

on:
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows'
            os: windows-latest
            generator: 'Visual Studio 17.8 2022'
            arch: '-A x64'
          - name: 'Linux'
            os: ubuntu-latest
            env:
              CC: gcc-11
              CXX: g++-11

    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update && sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
          fi
      - name: Build vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '943c5ef1c8f6b5e6ced092b242c8299caae2ff01'

      - name: Build project
        run: |
          cmake . -B build -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE="Release"
          cmake --build build --config Release